outdir: out
logdir: log

samples:
    sampleA: /path/to/sampleA/fastq
    sampleB: /path/to/sampleB/fastq
    sampleC: /path/to/sampleC/fastq

genome:
    /path/to/database/genome.fa.gz

annotbed:
    /path/to/database/annotation.bed.gz

vcfanno_conf:
    /path/to/configuration/vcfanno_conf.toml

parameters:
    survivor_distance: 500

last-train:
    pass # created by rule last_prepare

last-index:
    pass # created by rule last_prepare

refgene:
    pass # http://hgdownload.cse.ucsc.edu/goldenPath/hg38/database/refGene.txt.gz

microsat:
    pass # http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/microsat.txt.gz

resources:
    default:
        mem: 2000
        walltime: 120
        threads: 1
    nglmr_align:
        mem: 64000
        walltime: 1440
        threads: 36
    samtools_index:
        threads: 4
