name: nano-snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex
  - atk
  - bamtools
  - bcftools
  - biopython
  - blas
  - blast
  - boost
  - boost-cpp
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - click
  - coloredlogs
  - curl
  - cycler
  - cyvcf2
  - dbus
  - decorator
  - expat
  - fontconfig
  - freetype
  - gdk-pixbuf
  - gettext
  - glib
  - gmp
  - gnutls
  - gobject-introspection
  - graphite2
  - gsl
  - gstreamer
  - gtk2
  - harfbuzz
  - htslib
  - humanfriendly
  - icu
  - intel-openmp
  - jpeg
  - kiwisolver
  - krb5
  - libcurl
  - libdeflate
  - libedit
  - libffi
  - libgcc
  - libgcc-ng
  - libgfortran
  - libgfortran-ng
  - libiconv
  - libpng
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxml2
  - matplotlib
  - matplotlib-base
  - matplotlib-venn
  - minimap2
  - mkl
  - mkl_fft
  - mkl_random
  - mosdepth
  - nanosv
  - ncurses
  - nettle
  - networkx
  - ngmlr
  - npinv
  - numpy
  - numpy-base
  - openjdk
  - openssl
  - pandas
  - pango
  - patsy
  - pbsv
  - pcre
  - perl
  - perl-archive-tar
  - perl-carp
  - perl-compress-raw-bzip2
  - perl-compress-raw-zlib
  - perl-exporter
  - perl-exporter-tiny
  - perl-extutils-makemaker
  - perl-io-compress
  - perl-io-zlib
  - perl-list-moreutils
  - perl-list-moreutils-xs
  - perl-pathtools
  - perl-scalar-list-utils
  - perl-test-more
  - perl-xsloader
  - pip
  - pixman
  - pthread-stubs
  - pyparsing
  - pyqt
  - pysam
  - python
  - python-dateutil
  - pytz
  - pyvcf
  - qt
  - r-base
  - readline
  - samtools
  - scipy
  - seaborn
  - setuptools
  - sip
  - six
  - sniffles
  - sqlite
  - statsmodels
  - survivor
  - svim
  - tandem-genotypes
  - tclap
  - tk
  - tornado
  - vcfanno
  - vcftools
  - wheel
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - pip:
    - nanomath
    - upsetplot
